In [4]:
import pandas as pd
import yfinance as yf

In [2]:
d = pd.read_csv("index-constituent/nifty-200.csv")
d.head()

                          name            industry         symbol
0             360 ONE WAM Ltd.  Financial Services      360ONE.NS
1               ABB India Ltd.       Capital Goods         ABB.NS
2        APL Apollo Tubes Ltd.       Capital Goods   APLAPOLLO.NS
3   AU Small Finance Bank Ltd.  Financial Services      AUBANK.NS
4  Adani Energy Solutions Ltd.               Power  ADANIENSOL.NS

In [3]:
tickers = d["symbol"].tolist()
print(tickers)

['360ONE.NS', 'ABB.NS', 'APLAPOLLO.NS', 'AUBANK.NS', 'ADANIENSOL.NS', 'ADANIENT.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'ATGL.NS', 'ABCAPITAL.NS', 'ALKEM.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS', 'ASTRAL.NS', 'AUROPHARMA.NS', 'DMART.NS', 'AXISBANK.NS', 'BSE.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BAJAJHLDNG.NS', 'BANKBARODA.NS', 'BANKINDIA.NS', 'BDL.NS', 'BEL.NS', 'BHARATFORG.NS', 'BHEL.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'GROWW.NS', 'BIOCON.NS', 'BLUESTARCO.NS', 'BOSCHLTD.NS', 'BRITANNIA.NS', 'CGPOWER.NS', 'CANBK.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'COALINDIA.NS', 'COCHINSHIP.NS', 'COFORGE.NS', 'COLPAL.NS', 'CONCOR.NS', 'COROMANDEL.NS', 'CUMMINSIND.NS', 'DLF.NS', 'DABUR.NS', 'DIVISLAB.NS', 'DIXON.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'ETERNAL.NS', 'EXIDEIND.NS', 'NYKAA.NS', 'FEDERALBNK.NS', 'FORTIS.NS', 'GAIL.NS', 'GVT&D.NS', 'GMRAIRPORT.NS', 'GLENMARK.NS', 'GODFRYPHLP.NS', 'GODREJCP.NS', 'GODREJPROP.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCAMC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HAVELLS.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS', 'HAL.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'HINDZINC.NS', 'POWERINDIA.NS', 'HUDCO.NS', 'HYUNDAI.NS', 'ICICIBANK.NS', 'ICICIGI.NS', 'ICICIAMC.NS', 'IDFCFIRSTB.NS', 'ITC.NS', 'INDIANB.NS', 'INDHOTEL.NS', 'IOC.NS', 'IRCTC.NS', 'IRFC.NS', 'IREDA.NS', 'INDUSTOWER.NS', 'INDUSINDBK.NS', 'NAUKRI.NS', 'INFY.NS', 'INDIGO.NS', 'JSWENERGY.NS', 'JSWSTEEL.NS', 'JINDALSTEL.NS', 'JIOFIN.NS', 'JUBLFOOD.NS', 'KEI.NS', 'KPITTECH.NS', 'KALYANKJIL.NS', 'KOTAKBANK.NS', 'LTF.NS', 'LGEINDIA.NS', 'LICHSGFIN.NS', 'LTM.NS', 'LT.NS', 'LAURUSLABS.NS', 'LENSKART.NS', 'LODHA.NS', 'LUPIN.NS', 'MRF.NS', 'M&MFIN.NS', 'M&M.NS', 'MANKIND.NS', 'MARICO.NS', 'MARUTI.NS', 'MFSL.NS', 'MAXHEALTH.NS', 'MAZDOCK.NS', 'MOTILALOFS.NS', 'MPHASIS.NS', 'MCX.NS', 'MUTHOOTFIN.NS', 'NHPC.NS', 'NMDC.NS', 'NTPC.NS', 'NATIONALUM.NS', 'NESTLEIND.NS', 'OBEROIRLTY.NS', 'ONGC.NS', 'OIL.NS', 'PAYTM.NS', 'OFSS.NS', 'POLICYBZR.NS', 'PIIND.NS', 'PAGEIND.NS', 'PATANJALI.NS', 'PERSISTENT.NS', 'PHOENIXLTD.NS', 'PIDILITIND.NS', 'POLYCAB.NS', 'PFC.NS', 'POWERGRID.NS', 'PREMIERENE.NS', 'PRESTIGE.NS', 'PNB.NS', 'RECLTD.NS', 'RADICO.NS', 'RVNL.NS', 'RELIANCE.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SRF.NS', 'MOTHERSON.NS', 'SHREECEM.NS', 'SHRIRAMFIN.NS', 'ENRIN.NS', 'SIEMENS.NS', 'SOLARINDS.NS', 'SBIN.NS', 'SAIL.NS', 'SUNPHARMA.NS', 'SUPREMEIND.NS', 'SUZLON.NS', 'SWIGGY.NS', 'TVSMOTOR.NS', 'TATACAP.NS', 'TATACOMM.NS', 'TCS.NS', 'TATACONSUM.NS', 'TATAELXSI.NS', 'TATAINVEST.NS', 'TMCV.NS', 'TMPV.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TRENT.NS', 'TIINDIA.NS', 'UPL.NS', 'ULTRACEMCO.NS', 'UNIONBANK.NS', 'UNITDSPR.NS', 'VBL.NS', 'VEDL.NS', 'VMM.NS', 'IDEA.NS', 'VOLTAS.NS', 'WAAREEENER.NS', 'WIPRO.NS', 'YESBANK.NS', 'ZYDUSLIFE.NS']

In [6]:
data = yf.download(tickers, interval="1d", period="max", auto_adjust=True)
data

[*********************100%***********************]  200 of 200 completed

Price             Close                                                  \
Ticker        360ONE.NS  ABB.NS ABCAPITAL.NS ADANIENSOL.NS  ADANIENT.NS
Date
1996-01-01          NaN     NaN          NaN           NaN          NaN
1996-01-02          NaN     NaN          NaN           NaN          NaN
1996-01-03          NaN     NaN          NaN           NaN          NaN
1996-01-04          NaN     NaN          NaN           NaN          NaN
1996-01-05          NaN     NaN          NaN           NaN          NaN
...                 ...     ...          ...           ...          ...
2026-04-17  1113.300049  7029.5   340.399994   1259.800049  2218.300049
2026-04-20  1109.250000  7158.0   341.600006   1259.400024  2229.600098
2026-04-21  1108.349976  7255.0   344.600006   1265.300049  2226.000000
2026-04-22  1054.900024  7587.0   350.700012   1368.099976  2260.800049
2026-04-23  1042.949951  7590.0   349.850006   1375.500000  2303.000000

Price                                                                       \
Ticker     ADANIGREEN.NS ADANIPORTS.NS ADANIPOWER.NS ALKEM.NS AMBUJACEM.NS
Date
1996-01-01           NaN           NaN           NaN      NaN          NaN
1996-01-02           NaN           NaN           NaN      NaN          NaN
1996-01-03           NaN           NaN           NaN      NaN          NaN
1996-01-04           NaN           NaN           NaN      NaN          NaN
1996-01-05           NaN           NaN           NaN      NaN          NaN
...                  ...           ...           ...      ...          ...
2026-04-17   1127.300049   1573.400024    198.500000   5582.0   459.000000
2026-04-20   1152.699951   1578.400024    200.830002   5642.0   454.899994
2026-04-21   1150.000000   1594.099976    202.979996   5696.5   456.250000
2026-04-22   1198.949951   1588.599976    215.649994   5627.0   460.899994
2026-04-23   1225.550049   1600.400024    214.199997   5457.0   452.850006

Price       ...      Volume                                                 \
Ticker      ... UNITDSPR.NS     UPL.NS      VBL.NS     VEDL.NS      VMM.NS
Date        ...
1996-01-01  ...         NaN        NaN         NaN     44000.0         NaN
1996-01-02  ...         NaN        NaN         NaN     34000.0         NaN
1996-01-03  ...         NaN        NaN         NaN     16000.0         NaN
1996-01-04  ...         NaN        NaN         NaN     24000.0         NaN
1996-01-05  ...         NaN        NaN         NaN     10000.0         NaN
...         ...         ...        ...         ...         ...         ...
2026-04-17  ...   2825738.0  1023994.0  11968336.0   9934013.0  30756989.0
2026-04-20  ...   1189368.0  1301749.0   6027104.0  10554185.0  11543591.0
2026-04-21  ...   2334336.0  1144716.0   7932444.0  30562626.0  18492065.0
2026-04-22  ...   1841125.0  1709380.0  11943145.0  14257215.0  10236146.0
2026-04-23  ...    424921.0  1060460.0   6191088.0  10427237.0  16258894.0

Price
Ticker      VOLTAS.NS WAAREEENER.NS    WIPRO.NS   YESBANK.NS ZYDUSLIFE.NS
Date
1996-01-01        NaN           NaN     39999.0          NaN          NaN
1996-01-02        NaN           NaN     79999.0          NaN          NaN
1996-01-03        NaN           NaN     39999.0          NaN          NaN
1996-01-04        NaN           NaN    239999.0          NaN          NaN
1996-01-05        NaN           NaN         0.0          NaN          NaN
...               ...           ...         ...          ...          ...
2026-04-17  1266294.0     3722006.0  80542603.0  130228329.0     504613.0
2026-04-20  1789507.0     1553640.0  27927164.0  379799755.0     459049.0
2026-04-21  1068169.0     1477569.0  21530723.0   96821013.0     318304.0
2026-04-22   865864.0     1301434.0  21790433.0  100201392.0     290532.0
2026-04-23   759836.0      860447.0   7916193.0   45777296.0    1196363.0

[7609 rows x 1000 columns]

In [ ]:
file_name = "nifty-200.csv"
data.to_csv(f"data/index-stocks-data/{file_name}", index=True)