In [1]:
import pandas as pd

In [2]:
raw_data = pd.read_csv("data/raw-data/ind_nifty50list.csv")

In [3]:
raw_data.head()

,Company Name,Industry,Symbol,Series,ISIN Code
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT,EQ,INE423A01024
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP,EQ,INE437A01024
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT,EQ,INE021A01026
4,Axis Bank Ltd.,Financial Services,AXISBANK,EQ,INE238A01034

In [4]:
raw_data["Series"].value_counts()

Series
EQ    50
Name: count, dtype: int64

In [5]:
raw_data["Industry"].value_counts()

Industry
Financial Services                11
Healthcare                         5
Automobile and Auto Components     5
Information Technology             5
Metals & Mining                    4
Fast Moving Consumer Goods         4
Oil Gas & Consumable Fuels         3
Services                           2
Consumer Durables                  2
Consumer Services                  2
Construction Materials             2
Power                              2
Capital Goods                      1
Telecommunication                  1
Construction                       1
Name: count, dtype: int64

In [6]:
raw_data.drop(columns=["Series", "ISIN Code"], inplace=True)
raw_data.head()

                                 Company Name            Industry      Symbol
0                      Adani Enterprises Ltd.     Metals & Mining    ADANIENT
1  Adani Ports and Special Economic Zone Ltd.            Services  ADANIPORTS
2            Apollo Hospitals Enterprise Ltd.          Healthcare  APOLLOHOSP
3                           Asian Paints Ltd.   Consumer Durables  ASIANPAINT
4                              Axis Bank Ltd.  Financial Services    AXISBANK

In [7]:
raw_data.columns = ["name", "industry", "symbol"]

In [8]:
raw_data["symbol"] = raw_data["symbol"] + ".NS"
raw_data.head()

,name,industry,symbol
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT.NS
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS.NS
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP.NS
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT.NS
4,Axis Bank Ltd.,Financial Services,AXISBANK.NS

In [9]:
file_name = "nifty-50.csv"
raw_data.to_csv(f"data/index-constituent/{file_name}", index=False)