In [1]:
import pandas as pd
import yfinance as yf

In [2]:
d = pd.read_csv("data/index-constituent/nifty-50.csv")
d.head()

,name,industry,symbol
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT.NS
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS.NS
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP.NS
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT.NS
4,Axis Bank Ltd.,Financial Services,AXISBANK.NS

In [3]:
tickers = d["symbol"].tolist()
print(tickers)

['ADANIENT.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BEL.NS', 'BHARTIARTL.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'ETERNAL.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ITC.NS', 'INFY.NS', 'INDIGO.NS', 'JSWSTEEL.NS', 'JIOFIN.NS', 'KOTAKBANK.NS', 'LT.NS', 'M&M.NS', 'MARUTI.NS', 'MAXHEALTH.NS', 'NTPC.NS', 'NESTLEIND.NS', 'ONGC.NS', 'POWERGRID.NS', 'RELIANCE.NS', 'SBILIFE.NS', 'SHRIRAMFIN.NS', 'SBIN.NS', 'SUNPHARMA.NS', 'TCS.NS', 'TATACONSUM.NS', 'TMPV.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'TRENT.NS', 'ULTRACEMCO.NS', 'WIPRO.NS']

In [4]:
data = yf.download(tickers, interval="1d", period="max", auto_adjust=True)
data

[*********************100%***********************]  50 of 50 completed

Price             Close                                            \
Ticker      ADANIENT.NS ADANIPORTS.NS APOLLOHOSP.NS ASIANPAINT.NS
Date
1996-01-01          NaN           NaN           NaN           NaN
1996-01-02          NaN           NaN           NaN           NaN
1996-01-03          NaN           NaN           NaN           NaN
1996-01-04          NaN           NaN           NaN           NaN
1996-01-05          NaN           NaN           NaN           NaN
...                 ...           ...           ...           ...
2026-04-17  2218.300049   1573.400024        7699.0   2464.000000
2026-04-20  2229.600098   1578.400024        7657.0   2516.800049
2026-04-21  2226.000000   1594.099976        7744.0   2543.600098
2026-04-22  2260.800049   1588.599976        7662.0   2562.899902
2026-04-23  2296.600098   1600.099976        7723.5   2532.699951

Price                                                                          \
Ticker      AXISBANK.NS BAJAJ-AUTO.NS BAJAJFINSV.NS BAJFINANCE.NS      BEL.NS
Date
1996-01-01          NaN           NaN           NaN           NaN         NaN
1996-01-02          NaN           NaN           NaN           NaN         NaN
1996-01-03          NaN           NaN           NaN           NaN         NaN
1996-01-04          NaN           NaN           NaN           NaN         NaN
1996-01-05          NaN           NaN           NaN           NaN         NaN
...                 ...           ...           ...           ...         ...
2026-04-17  1359.099976        9773.5   1838.900024    908.250000  462.750000
2026-04-20  1354.699951        9803.0   1830.599976    917.750000  457.549988
2026-04-21  1377.699951        9793.0   1851.400024    938.849976  451.500000
2026-04-22  1379.599976        9602.0   1842.900024    934.750000  448.700012
2026-04-23  1373.199951        9555.0   1801.000000    917.799988  447.100006

Price                     ...       Volume                             \
Ticker     BHARTIARTL.NS  ... SUNPHARMA.NS TATACONSUM.NS TATASTEEL.NS
Date                      ...
1996-01-01           NaN  ...      38730.0       23500.0   10242229.0
1996-01-02           NaN  ...      77460.0       23000.0   16954313.0
1996-01-03           NaN  ...      12910.0       21000.0   13514114.0
1996-01-04           NaN  ...      64550.0      133000.0   34785820.0
1996-01-05           NaN  ...      12910.0      114500.0   30138033.0
...                  ...  ...          ...           ...          ...
2026-04-17   1846.900024  ...    3146482.0     1287668.0   22837792.0
2026-04-20   1846.099976  ...    1834532.0     1132404.0   24992602.0
2026-04-21   1855.000000  ...    3631490.0     1072221.0   17427021.0
2026-04-22   1829.000000  ...    2169514.0     4284220.0   20795714.0
2026-04-23   1831.199951  ...    1595422.0      584421.0   11352650.0

Price                                                                \
Ticker         TCS.NS    TECHM.NS   TITAN.NS     TMPV.NS   TRENT.NS
Date
1996-01-01        NaN         NaN     4000.0         NaN        NaN
1996-01-02        NaN         NaN    24000.0         NaN        NaN
1996-01-03        NaN         NaN    22000.0         NaN        NaN
1996-01-04        NaN         NaN    46000.0         NaN        NaN
1996-01-05        NaN         NaN    20000.0         NaN        NaN
...               ...         ...        ...         ...        ...
2026-04-17  2718206.0   1859402.0  2124034.0   7314044.0  1248606.0
2026-04-20  2288558.0   1341688.0  1646815.0   7216605.0  2228155.0
2026-04-21  2719959.0   2001948.0   656106.0   5922373.0  2438074.0
2026-04-22  5232045.0  11668801.0   596352.0  14994310.0  2596869.0
2026-04-23  1409136.0   2337108.0   451668.0   5107697.0  3366515.0

Price
Ticker     ULTRACEMCO.NS    WIPRO.NS
Date
1996-01-01           NaN     39999.0
1996-01-02           NaN     79999.0
1996-01-03           NaN     39999.0
1996-01-04           NaN    239999.0
1996-01-05           NaN         0.0
...                  ...         ...
2026-04-17      165109.0  80542603.0
2026-04-20      335624.0  27927164.0
2026-04-21      320111.0  21530723.0
2026-04-22      312307.0  21790433.0
2026-04-23      124857.0   8365765.0

[7609 rows x 250 columns]

In [5]:
file_name = "nifty-50.csv"
data.to_csv(f"data/index-stocks-data/{file_name}", index=True)