In [8]:
import pandas as pd

In [9]:
raw_data = pd.read_csv("raw-data/ind_nifty200list.csv")

In [10]:
raw_data.head()

,Company Name,Industry,Symbol,Series,ISIN Code
0,360 ONE WAM Ltd.,Financial Services,360ONE,EQ,INE466L01038
1,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022
2,APL Apollo Tubes Ltd.,Capital Goods,APLAPOLLO,EQ,INE702C01027
3,AU Small Finance Bank Ltd.,Financial Services,AUBANK,EQ,INE949L01017
4,Adani Energy Solutions Ltd.,Power,ADANIENSOL,EQ,INE931S01010

In [11]:
raw_data["Series"].value_counts()

Series
EQ    200
Name: count, dtype: int64

In [12]:
raw_data["Industry"].value_counts()

Industry
Financial Services                48
Capital Goods                     23
Healthcare                        16
Automobile and Auto Components    14
Fast Moving Consumer Goods        14
Information Technology            12
Consumer Services                 11
Metals & Mining                   10
Oil Gas & Consumable Fuels         9
Power                              8
Consumer Durables                  8
Chemicals                          6
Realty                             6
Services                           4
Construction Materials             4
Telecommunication                  4
Construction                       2
Textiles                           1
Name: count, dtype: int64

In [13]:
raw_data.drop(columns=["Series", "ISIN Code"], inplace=True)
raw_data.head()

                  Company Name            Industry      Symbol
0             360 ONE WAM Ltd.  Financial Services      360ONE
1               ABB India Ltd.       Capital Goods         ABB
2        APL Apollo Tubes Ltd.       Capital Goods   APLAPOLLO
3   AU Small Finance Bank Ltd.  Financial Services      AUBANK
4  Adani Energy Solutions Ltd.               Power  ADANIENSOL

In [14]:
raw_data.columns = ["name", "industry", "symbol"]

In [16]:
raw_data["symbol"] = raw_data["symbol"] + ".NS"
raw_data.head()

                          name            industry         symbol
0             360 ONE WAM Ltd.  Financial Services      360ONE.NS
1               ABB India Ltd.       Capital Goods         ABB.NS
2        APL Apollo Tubes Ltd.       Capital Goods   APLAPOLLO.NS
3   AU Small Finance Bank Ltd.  Financial Services      AUBANK.NS
4  Adani Energy Solutions Ltd.               Power  ADANIENSOL.NS

In [17]:
file_name = "nifty-200.csv"
raw_data.to_csv(f"index-constituent/{file_name}", index=False)